"""Add practice_images to Course model

Revision ID: 229774e93428
Revises: bd98cb64145a
Create Date: 2025-03-10 23:40:50.912626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229774e93428'
down_revision: Union[str, None] = 'bd98cb64145a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('practice_images', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'practice_images')
    # ### end Alembic commands ###
