"""Add CourseType and Course models

Revision ID: 7f0aafa87d3b
Revises: d972357e4f2c
Create Date: 2025-03-10 17:05:11.377004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0aafa87d3b'
down_revision: Union[str, None] = 'd972357e4f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('banner_file_id', sa.String(length=255), nullable=True),
    sa.Column('video_file_id', sa.String(length=255), nullable=True),
    sa.Column('voice_file_id', sa.String(length=255), nullable=True),
    sa.Column('text_explanation', sa.Text(), nullable=True),
    sa.Column('has_poll', sa.Boolean(), nullable=True),
    sa.Column('poll_question', sa.Text(), nullable=True),
    sa.Column('poll_options', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['course_type_id'], ['course_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    op.drop_table('course_types')
    # ### end Alembic commands ###
