"""New field added is_paid

Revision ID: b911d955077f
Revises: af2256b63eb9
Create Date: 2025-02-20 12:28:27.091075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b911d955077f'
down_revision: Union[str, None] = 'af2256b63eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_paid')
    # ### end Alembic commands ###
