"""Courses and Type of Courses model is created

Revision ID: e39df2434a58
Revises: b911d955077f
Create Date: 2025-03-10 16:54:11.643789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39df2434a58'
down_revision: Union[str, None] = 'b911d955077f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('courses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('course_type_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('banner_file_id', sa.String(length=255), nullable=True),
        sa.Column('video_file_id', sa.String(length=255), nullable=True),
        sa.Column('voice_file_id', sa.String(length=255), nullable=True),
        sa.Column('text_explanation', sa.Text(), nullable=True),
        sa.Column('has_poll', sa.Boolean(), default=False),
        sa.Column('poll_question', sa.Text(), nullable=True),
        sa.Column('poll_options', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.Column('order_index', sa.Integer(), default=0),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['course_type_id'], ['course_types.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    op.drop_table('course_types')
    # ### end Alembic commands ###
