[tool.poetry]
name = "poetry-package-managment"
version = "0.1.0"
description = ""
authors = ["kovanskiy <jjjorik1997@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.18.0"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
asyncpg = "^0.30.0"
sqlalchemy = "^2.0.38"
alembic = "^1.14.1"
coloredlogs = "^15.0.1"
rich = "^13.9.4"
psycopg2-binary = "^2.9.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
